/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import internet.HTTPConnection;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author SKings
 */
public class MainFrame extends JFrame {

    /**
     * Creates new form MainFrame
     */
    int posX = 0, posY = 0;
    final Color myRed = new Color(255, 10, 10, 255), myGreen = new Color(0, 204, 51, 255);

    public MainFrame() {
        this.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                mousePressedCore(e);
            }
        });

        this.addMouseMotionListener(new MouseAdapter() {
            public void mouseDragged(MouseEvent evt) {
                //sets frame position when mouse dragged			
                mouseDragedCore(evt);
            }
        });

        initComponents();

        mainPanel.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent evt) {
                mousePressedCore(evt);
            }
        });
        mainPanel.addMouseMotionListener(new MouseAdapter() {
            public void mouseDragged(MouseEvent evt) {
                //sets frame position when mouse dragged			
                mouseDragedCore(evt);

            }
        });
        // set location of frame at center
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        // put caret at end of text
        urlJText.setCaretPosition(urlJText.getText().length());
        urlJText.requestFocus();
    }

    public void mousePressedCore(MouseEvent evt) {
        posX = evt.getX();
        posY = evt.getY();
    }

    public void mouseDragedCore(MouseEvent evt) {
        setLocation(evt.getXOnScreen() - posX, evt.getYOnScreen() - posY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        mainPanel = new javax.swing.JPanel();
        httpImgLabel = new javax.swing.JLabel();
        exitImgLabel = new javax.swing.JLabel();
        miniImgLabel = new javax.swing.JLabel();
        urlPanel = new javax.swing.JPanel();
        urlJText = new javax.swing.JTextField();
        wwwImgLbl = new javax.swing.JLabel();
        goImgLbl = new javax.swing.JLabel();
        persisJradio = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        resJTextArea = new javax.swing.JTextArea();
        reqJLb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SKings HTTP Analyzer");
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImage(new ImageIcon("src\\UI\\logoHttp.png").getImage());
        setResizable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${true}"), this, org.jdesktop.beansbinding.BeanProperty.create("undecorated"));
        bindingGroup.addBinding(binding);

        mainPanel.setBackground(new java.awt.Color(25, 25, 25));
        mainPanel.setToolTipText("");

        httpImgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/http-search-symbol.png"))); // NOI18N
        httpImgLabel.setToolTipText("HTTP");
        httpImgLabel.setVerifyInputWhenFocusTarget(false);

        exitImgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/white-cancel-button.png"))); // NOI18N
        exitImgLabel.setToolTipText("Exit");
        exitImgLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitImgLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitImgLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitImgLabelMouseExited(evt);
            }
        });

        miniImgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/white-mini.png"))); // NOI18N
        miniImgLabel.setToolTipText("Minimize");
        miniImgLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniImgLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniImgLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniImgLabelMouseExited(evt);
            }
        });

        urlPanel.setBackground(new java.awt.Color(50, 50, 50));

        urlJText.setBackground(new java.awt.Color(50, 50, 50));
        urlJText.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        urlJText.setForeground(new java.awt.Color(0, 153, 0));
        urlJText.setText("http://www.");
        urlJText.setToolTipText("URL");
        urlJText.setBorder(null);
        urlJText.setCaretColor(new java.awt.Color(51, 153, 0));
        urlJText.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        urlJText.setMargin(new java.awt.Insets(10, 10, 10, 10));
        urlJText.setName(""); // NOI18N
        urlJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlJTextActionPerformed(evt);
            }
        });

        wwwImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/www.png"))); // NOI18N
        wwwImgLbl.setToolTipText("WWW");

        goImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/white-go.png"))); // NOI18N
        goImgLbl.setToolTipText("GO");
        goImgLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goImgLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                goImgLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                goImgLblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout urlPanelLayout = new javax.swing.GroupLayout(urlPanel);
        urlPanel.setLayout(urlPanelLayout);
        urlPanelLayout.setHorizontalGroup(
            urlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, urlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wwwImgLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(urlJText, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(goImgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        urlPanelLayout.setVerticalGroup(
            urlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(urlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(urlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(wwwImgLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(urlJText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goImgLbl, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        urlJText.getAccessibleContext().setAccessibleName("urlJText");

        persisJradio.setBackground(new java.awt.Color(25, 25, 25));
        persisJradio.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        persisJradio.setForeground(new java.awt.Color(0, 204, 51));
        persisJradio.setSelected(true);
        persisJradio.setText("Persistent");
        persisJradio.setToolTipText("Persistent Connection");
        persisJradio.setBorder(null);
        persisJradio.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jScrollPane2.setBackground(new java.awt.Color(60, 60, 60));
        jScrollPane2.setForeground(new java.awt.Color(0, 204, 51));
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        resJTextArea.setEditable(false);
        resJTextArea.setBackground(new java.awt.Color(60, 60, 60));
        resJTextArea.setColumns(20);
        resJTextArea.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        resJTextArea.setForeground(new java.awt.Color(0, 204, 51));
        resJTextArea.setRows(5);
        resJTextArea.setText("Response Message to HEAD and OPTIONS method in HTTP to URL that you write will be shown.");
        resJTextArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        resJTextArea.setCaretColor(new java.awt.Color(60, 60, 60));
        resJTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        resJTextArea.setDisabledTextColor(new java.awt.Color(0, 204, 51));
        resJTextArea.setFocusable(false);
        resJTextArea.setMargin(new java.awt.Insets(20, 20, 20, 20));
        jScrollPane2.setViewportView(resJTextArea);

        reqJLb.setBackground(new java.awt.Color(25, 25, 25));
        reqJLb.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        reqJLb.setForeground(new java.awt.Color(0, 204, 51));
        reqJLb.setText("Response");
        reqJLb.setToolTipText("");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(urlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(httpImgLabel)
                                .addGap(655, 655, 655)
                                .addComponent(miniImgLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exitImgLabel)))
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addComponent(reqJLb, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(persisJradio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(654, 654, 654))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(miniImgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitImgLabel)
                    .addComponent(httpImgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(urlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(persisJradio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reqJLb, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        httpImgLabel.getAccessibleContext().setAccessibleName("httpImgLabel");
        httpImgLabel.getAccessibleContext().setAccessibleDescription("");
        httpImgLabel.getAccessibleContext().setAccessibleParent(mainPanel);
        exitImgLabel.getAccessibleContext().setAccessibleName("exitImgLAbel");
        miniImgLabel.getAccessibleContext().setAccessibleName("miniImgLabel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitImgLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitImgLabelMouseEntered
        // TODO add your handling code here:
        exitImgLabel.setIcon(new ImageIcon(getClass().getResource("/UI/red-cancel-button.png")));
    }//GEN-LAST:event_exitImgLabelMouseEntered

    private void exitImgLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitImgLabelMouseExited
        // TODO add your handling code here:
        exitImgLabel.setIcon(new ImageIcon(getClass().getResource("/UI/white-cancel-button.png")));
    }//GEN-LAST:event_exitImgLabelMouseExited

    private void exitImgLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitImgLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitImgLabelMouseClicked

    private void miniImgLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniImgLabelMouseEntered
        // TODO add your handling code here:
        miniImgLabel.setIcon(new ImageIcon(getClass().getResource("/UI/green-mini.png")));
    }//GEN-LAST:event_miniImgLabelMouseEntered

    private void miniImgLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniImgLabelMouseExited
        // TODO add your handling code here:
        miniImgLabel.setIcon(new ImageIcon(getClass().getResource("/UI/white-mini.png")));
    }//GEN-LAST:event_miniImgLabelMouseExited

    private void miniImgLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniImgLabelMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_miniImgLabelMouseClicked

    private void urlJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlJTextActionPerformed
        // TODO add your handling code here:
        goToUrlAction();
    }//GEN-LAST:event_urlJTextActionPerformed

    private void goImgLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goImgLblMouseExited
        // TODO add your handling code here:
        goImgLbl.setIcon(new ImageIcon(getClass().getResource("/UI/white-go.png")));
    }//GEN-LAST:event_goImgLblMouseExited

    private void goImgLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goImgLblMouseEntered
        // TODO add your handling code here:
        goImgLbl.setIcon(new ImageIcon(getClass().getResource("/UI/green-go.png")));
    }//GEN-LAST:event_goImgLblMouseEntered

    private void goImgLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goImgLblMouseClicked
        // TODO add your handling code here:
        goToUrlAction();
    }//GEN-LAST:event_goImgLblMouseClicked

    private void goToUrlAction() {
        HTTPConnection httpConnection = new HTTPConnection();
        String responseTxt = httpConnection.excute(urlJText.getText(), persisJradio.isSelected());
        String[] parts = responseTxt.split("\n");
        if ("red".equalsIgnoreCase(parts[0])) {
            resJTextArea.setForeground(myRed);
        } else {
            resJTextArea.setForeground(myGreen);
        }
        responseTxt = responseTxt.substring(responseTxt.indexOf('\n') + 1);
        resJTextArea.setText(responseTxt);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitImgLabel;
    private javax.swing.JLabel goImgLbl;
    private javax.swing.JLabel httpImgLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel miniImgLabel;
    private javax.swing.JRadioButton persisJradio;
    private javax.swing.JLabel reqJLb;
    private javax.swing.JTextArea resJTextArea;
    private javax.swing.JTextField urlJText;
    private javax.swing.JPanel urlPanel;
    private javax.swing.JLabel wwwImgLbl;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
